### ISSUE TITLE
Navbar Shifts Right

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#101]
Trigger any modal. Notice that when it opens/closes, the homepage navbar shifts right and left, which also causes the browser scroll bar to disappear/re-appear.

**Comment by snuka** [comment]
http://stackoverflow.com/questions/19960162/bootstrap-3-modal-fires-and-causes-page-to-shift-to-the-left-momentarily-brows

**Comment by snuka** [comment]
Had to use a very ugly hack solution, but it looks like this is what Twitter suggests as the solution. So here is goes.

**Comment by ppzgenome** [comment]
Chris and i talked about the lesser of two evils: ok to shift nav bar, but dont destroy banner; dragging back to the staging column of work flow

**Comment by ppzgenome** [comment]
Going to close this issue out: at least the banner isn't broken as a result of fixing this. Essentially reverted to original bug of letting navbar shift right.
