### ISSUE TITLE
Profile Settings:Specific Update Notifications

### ISSUE THREAD

**Issue by snuka** [ycha28/resume_fixer#116]
Problem: 
1. Current "user setting updated" notification appears on the very top of the page so when the user is updating the profiles on the lower side of the page, the user cannot see the notification.
1. Once the user completes one of the profile category edits, "user setting updated" is populated. so when the user continues to update other categories, it is difficult to tell the update has been made because "user setting updated" message remains unchanged. 

Solution: Have a update notice on every line!

![uploads/2e844135-324f-4123-acb7-87d06a64c9cb/Profile Setting Layout.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2e844135-324f-4123-acb7-87d06a64c9cb%2FProfile+Setting+Layout.jpg)

**Comment by ppzgenome** [comment]
Not a bad idea; but upon further thought and discussion with Young, I think we can come up with a more elegant solution than this; only b/c the proposed is a bit too heavy handed. Let's follow Chris' thought process, but simply even more.

**Comment by ppzgenome** [comment]
we had an alternative solution to do field specific updated notifications but the library young was exploring was requiring way too much validation work to be re-done. the cost doesn't justify the gains at this point for our MVP. relegating issue for now.
