### ISSUE TITLE
My Documents Layout(Mockup)

### ISSUE THREAD

**Issue by snuka** [ycha28/resume_fixer#118]
1. Uploaded File: To solve the problem of having ridiculously file names that can mess up the layout, I propose just attaching a file icon. Thinking that the purpose of showing a preview+filename is to assure that the user has uploaded the right file, I think giving them an access of the preview will suffice. 
2. I put a change file button next to the "uploaded file" category when the user has not been matched with the editor yet. The only problem that I can foresee is when the user pays for a resume and than changes the file to a cover letter trying to take advantage of the price difference. That said since we do not have any automated way to verify whether the user submitted what he paid for, I think this is a problem that is inherent, not something that is newly caused the "change file" feature.
3. Due to the limited area of horizontal space, instead of putting a column that says "completed files" I suggest just putting completed file icons next to the completed status. To visually show the difference btw the uploaded file and the completed file, I put a border around the completed ones.
4. Young made a great suggestion to just show "view" instead of the first couple of words in the comment. I also agree. The columns would look quite messy with all the words from the comment being populated. 

![uploads/2aa0e1ea-f556-4564-a479-ec73207837b6/My documents.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2aa0e1ea-f556-4564-a479-ec73207837b6%2FMy+documents.jpg)

**Comment by ppzgenome** [comment]
Regarding #2, I agree it's a real issue. however, i think as an editor, you will be able to see File Type from the portal. once you open the file and notice it's not consistent with the listed file type, don't edit it. open a refund ticket.
