### ISSUE TITLE
UPDATED: Jumping Bug

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#128]
This bug is hard to reproduce... but occurs at the popular ipad size, so we need to address it:
1. Don't log in
2. Make browser narrow (but not until the icon menu appears)
3. click any navlink
4. section loads. 
5. now wait and watch
6. the page will shift up and down and up and down

**Comment by ppzgenome** [comment]
Double checked today: Problem persists across multiple computers in multiple browsers. This is not idiosyncratic to Paul's laptop alone. Granted it is a difficult bug to spot. 

The jumping bug is universal. I figured out it is a result of the overall banner issues. Banner #1's height is shorter than the other two, which is why when the banner auto scrolls between that banner and two other normal ones, overall content below them get pushed down and up to different heights, creating the illusion of jumping when your looking that the content below. 

Possible that this gets resolved with Chris' successful banner fix overall.

**Comment by snuka** [comment]
Can you check if this still exists even after the banner heights are identical?
