### ISSUE TITLE
Banners simply don't look right at all

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#130]
In fully expanded vs smaller browser sizes, i'm getting very different cut-offs for the banners. even though banner area/zone may change in size, it should be doing so proportionately. currently that's not the behavior.

**Comment by snuka** [comment]
Paul, I've tested a couple of different dimensions and it seems 1500 x 600 works good. Can you send me the banner of 1500 X 600 to my email?

**Comment by ppzgenome** [comment]
Sent.
