### ISSUE TITLE
"Change File" Notice

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#137]
In my doc view, click on the up arrow button. Replace existing content with the following:

NOTE: You may replace this document as long as the status is NOT “In Editing” or “Complete.”

NOTE: You may only substitute documents of the same type: cover letter for another cover letter, resume for another resume, or essay for another essay. If you replace with a mismatching document type, we will not edit it. We will issue an automatic refund for that document.

![uploads/aa562a25-7946-4b3d-bcce-d74d0a50c974/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faa562a25-7946-4b3d-bcce-d74d0a50c974%2Fblob)

**Comment by snuka** [comment]
Had to use a very ugly hack solution, but it looks like this is what Twitter suggests as the solution. So here is goes.
