### ISSUE TITLE
UPDATED: Right Align Abbreviated Menu Items

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#150]
1. Make browser narrow so that the menu collapses into the yellow icon menu in the upper right of navbar. 
2. click the icon to expand.
3. notice that the navlinks are left aligned upon expansion.
4. Let's RIGHT ALIGN them. 

Rationale: the icon is in the upper right hand corner. user's shouldn't have to move cursors all the way to the left of the screen to tap navlinks. keep consistent element locations.

**Comment by ppzgenome** [comment]
Not (entirely) fixed:
submenu items need to also be right aligned.

![uploads/5358c390-9dd6-43f8-8e59-6ddee4166daf/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5358c390-9dd6-43f8-8e59-6ddee4166daf%2Fblob)

**Comment by snuka** [comment]
I did align them right but the right alignment looks a bit weird. Check it out and let me know what you think the best solution is. 
![uploads/48f0a894-89ad-44f3-a66e-7c64ec353507/screenshot-localhost 3000 2015-05-22 16-38-09.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F48f0a894-89ad-44f3-a66e-7c64ec353507%2Fscreenshot-localhost+3000+2015-05-22+16-38-09.png)

**Comment by ppzgenome** [comment]
Can you do like below, without negatively affecting submenu behavior at normal browser width?

![uploads/f6d3c901-9598-4750-9634-11d7fad5df60/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff6d3c901-9598-4750-9634-11d7fad5df60%2Fblob)
