### ISSUE TITLE
Banner Click Bug

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#162]
1. Make browser narrow so that yellow icon menu appears in upper right
2. Log in
3. Click on "Documents" navlink to go my My Docs
4. Click UFO logo
5. Click either right/left arrow on banner. 
6. Notice that it opens the yellow icon menu instead of scrolling the banner

**Comment by snuka** [comment]
Found the JS causing the error:

agency.js

```
// Closes the Responsive Menu on Click outside Menu
$('body > *').not('nav').click(function() {
    if(!$('button.navbar-toggle').hasClass('collapsed')) {
        $('.navbar-toggle:visible').click();
    }
});
```
