### ISSUE TITLE
Feature: Admin Status Change

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#192]
Once admin uploads a file, we should change the user My Docs file status to Completed.

**Comment by ycha28** [comment]
To make this work:
Log into the admin CMS (www.beamdox.com/admin). Go to the Documents page. Edit a document and go to the bottom of the form. Upload a file for the "edited file" field and update. Go to the documents page for the user who originally uploaded the file, and click the down arrow next to the document's "Complete" status to download the newly edited file.

**Comment by ppzgenome** [comment]
Ok, the Status change part works, but more issues related, so I'll open new tickets for those.
