### ISSUE TITLE
UPDATED - Stripe: Show acceptable payment parties on the stripe modal

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#196]

**Comment by ppzgenome** [comment]
integrate the payment party icons; sent to Young's email

**Comment by ppzgenome** [comment]
Make this 2row x 3 column 

![uploads/8ca1e092-47df-412a-9097-62b0b958bdf9/Huboard.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8ca1e092-47df-412a-9097-62b0b958bdf9%2FHuboard.jpg)

**Comment by ycha28** [comment]
Credit cards are now displayed in 2x3 rows.
