### ISSUE TITLE
After first-time pay, the payment modal's "Pay" button is inactive

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#206]
1. make a first time submission and payment
2. now, we should have "stored" user credit card info
3. go to new submission page to submit another file
4. the payment modal now says you can choose existing card on file or use another card
5. notice though, that the PAY button is dead, so users can't just use card on file to proceed

![uploads/80757f4c-26c9-42aa-ba1c-4169db371fce/Huboard.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F80757f4c-26c9-42aa-ba1c-4169db371fce%2FHuboard.jpg)

**Comment by ycha28** [comment]
Unable to reproduce. Can you check if it's still an issue?

**Comment by ppzgenome** [comment]
We changed the overall UI now, s this doesn't apply anymore. closing.
