### ISSUE TITLE
Credit Card Field Restrictions

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#208]
Credit card expiration date:
-Restrict the month and year to #s only, and respectively, to 2 digits and 4 digits.
-Make year field bold

![uploads/20b298c9-b234-40b5-a519-0e965fae9b2c/Huboard.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F20b298c9-b234-40b5-a519-0e965fae9b2c%2FHuboard.jpg)

**Comment by ycha28** [comment]
I fixed the validation for the expiration date, but I can't make the year field bold since it's not a separate field anymore. I combined the month/year fields into one field instead.
