### ISSUE TITLE
Attach Button - Submit Docs Page

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#211]
We need to reconsider the Attach button. After polling some random people, their response was that the Drag & Drop is clear. But after dragging a file, and seeing the progress bar, they tried to click the Attach button again, believing that the drag/drop was just file loading, but the Attach button was for actually appending. This happened 7/7 people I watched without any questions. 

Solution Options:
1. We can rename the Attach button to something else, like Select Documents, or go back to "Browse"
2. If we put the progress bar below the button AND renamed it something else. The progress bar is supposed to be general information pertaining to file upload, regardless of Drag/Drop or browse methodology anyway. There is a technical problem: Young can't reverse the order of the progress bar b/c of library he's using. 
3. If we simply killed the button altogether. Obvious risk here is that there might be some idiots who don't know how to drag and drop. 

![uploads/0d511fd6-3f60-4cf6-bdcb-778a484809f3/Huboard.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0d511fd6-3f60-4cf6-bdcb-778a484809f3%2FHuboard.jpg)

**Comment by ycha28** [comment]
Paul, I talked it over with Chris, and I think the most sensible thing to do here is to just remove the button entirely. Let's talk this over in the morning.

**Comment by ppzgenome** [comment]
Option 3 - remove the button altogether.
