### ISSUE TITLE
NOT FIXED: Payment Modal - add spacing

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#215]
add a line break space into the arrow area

![uploads/ee7276a8-d9a8-451b-b044-07319ba93e05/Huboard.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fee7276a8-d9a8-451b-b044-07319ba93e05%2FHuboard.jpg)

**Comment by ppzgenome** [comment]
Still broken, based on testing; putting back into BackLog bucket

**Comment by snuka** [comment]
sorry think I missed this out. Re fixed it.
