### ISSUE TITLE
Email Confirmation of Submission Content Assymetry

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#229]
1. If you submit multiple files
2. You will receive a confirmation of submission
3. However, the content will only communicate details for 1 of the multiple files, instead of for all three.(bad)
4. We need to reflect info for all files submitted, b/c that gives a fair "receipt" of the transaction total and its items and reduces confusion to the user, who might think they only successfully submitted a subset of an entire transaction.

**Comment by ycha28** [comment]
I'm not able to reproduce this error. Here's what i'm seeing in my submission email:

![uploads/4052868a-4315-4f12-8b18-29a4e789b3be/Screen Shot 2015-06-01 at 9.55.44 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4052868a-4315-4f12-8b18-29a4e789b3be%2FScreen+Shot+2015-06-01+at+9.55.44+PM.png)
