### ISSUE TITLE
Our Story Timeline: Kill Vertical Grey Line @ End

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#24]
![image](https://cloud.githubusercontent.com/assets/5505469/7557122/92c3b1e8-f759-11e4-9891-da16e968f8c3.png)

**Comment by snuka** [comment]
Taking a careful look at the css, the solution is not technically difficult. But I need to tear down the whole accordian CSS to achieve this. Lowered the priority for now.
