### ISSUE TITLE
Sign Up with Facebook is missing

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#261]
This could be my bad memory.... didn't we have a Sign Up with FB option in this modal? 

![uploads/a1d017ab-1663-48b3-aa47-b50dcc8189a4/hu.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa1d017ab-1663-48b3-aa47-b50dcc8189a4%2Fhu.jpg)

**Comment by snuka** [comment]
I don't remember seeing one. I'll put it there

**Comment by snuka** [comment]
Yeah the reason it isn't there is your screen shot is "signup with email" the facebook signup comes before you open this.

**Comment by ppzgenome** [comment]
Got it. Closing issue.
