### ISSUE TITLE
User Settings --> "Profile"

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#42]
1. Replace "settings" with "profile" in both locations as indicated
2. Capitalize "Number" in phone number label

![uploads/94efdc0f-5b64-475e-a70d-f994298c2b6e/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F94efdc0f-5b64-475e-a70d-f994298c2b6e%2Fblob)

**Comment by snuka** [comment]
Completed: setting -> profile changed
Incompleted: capitalizing "number"
