### ISSUE TITLE
Cosmetic to the Checkbox in Submit Page

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#46]
1. Underline Terms of Service, Privacy Policy, and Refund Policy as indicated below.
2. Add one additional line break between the checkbox text and the "Submit & Pay" button.

![uploads/80a6e2ab-f200-4dbb-b3ca-0f4c68909ba7/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F80a6e2ab-f200-4dbb-b3ca-0f4c68909ba7%2Fblob)

**Comment by snuka** [comment]
the text is in a label_tag which makes it difficult to span individual words within the text.
