### ISSUE TITLE
CRITICAL - File Attachment Bug

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#48]
To create the bug do the following:
1. Select two files. Make sure one is acceptable file type (e.g. doc or .txt), and the other is a banned type (.ppt or .xls).
2. Drag into the drop zone. Note the expected error message detailing the banned file type.
3. Now select a DIFFERENT acceptable file type and drag/drop into the same zone. 
4. Notice that now, two files will populate the Selected Documents List below. It seems that the acceptable file type from the original batch selection has piggy-backed.

This is undesirable behavior, because it defies typical user expectations. Our logic should be: 

IF a group of selected files includes ANY banned file type (e.g. a heterogeneous mix of acceptable or banned types), then NO files in that batch should attach.
AND, subsequent attachment of acceptable file types SHOULD NOT allow any acceptable file type from the previous heterogeneous batch to attach either.

**Comment by ppzgenome** [comment]
Apparently the order in which the files are selected matters. The problem only occurs if the INVALID file type is selected first.

**Comment by ycha28** [comment]
To fix this bug, I removed all of dropzone's native error messages and constructed my own using rails flash messages. Let me know if this is ok.
