### ISSUE TITLE
Submit Button on Home Page

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#54]
IF, Pre- login, THEN clicking on Submit should initialize modal sign-up/login, and not redirect to static log in page. Since this capability exists with our sign-up/login navlinks, I assume we can replicate same modal effect here as well.

**Comment by snuka** [comment]
changed it but on my local environment the word "submit documents" turned into yellow after clicking it and stayed after logging in.

**Comment by ppzgenome** [comment]
Ok, will wait for your solution + push.

**Comment by ppzgenome** [comment]
reassigning to Young
