### ISSUE TITLE
Submission Confirmation Email to User

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#8]

**Comment by ycha28** [comment]
Emails are now being sent to users. I've created a template that's nearly identical to the one we're sending to our admins:

"Your submission has been received at Beamdox!

You've submitted the following documents for review:

Name: cover_letter.rtf
Type: resume
Total price: $100

We will now match your submission with one of our expert editors for review. To track the progress of your documents, visit http://localhost.com:3000/profile/documents."

Let me know what kind of wording you want for the final template.
