### ISSUE TITLE
Not Resolved: "Ease-In" effect is imprecise.

### ISSUE THREAD

**Issue by ppzgenome** [ycha28/resume_fixer#89]
1. Make your browser narrow so that the home page nav links double or triple the overall height of the navbar. (see both examples below). 
2. Now when you click on any of the navlinks, the ease-in effect will over shoot their sections and cut off the headers/subheaders.

![uploads/b07abaed-3c48-4040-973b-0fcd9ed2ce94/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb07abaed-3c48-4040-973b-0fcd9ed2ce94%2Fblob)

**Comment by snuka** [comment]
This was not a easy solve. I had to use multiple hacks but at least it works. 
1. Change "Our Story" -> "Story" (reducing the letters in the menu helps)
2. Reduce the font using a media query
3. Reduce the padding btw the menus when the windows are smaller

**Comment by ppzgenome** [comment]
Issue is not solved (entirely): Although solved when logged out, if you do log in, homepage navlinks double stacking still occurs when browser is set to ipad dimensions, causing imprecise ease-in effect when clicking navlinks. 

![uploads/680e41e6-722a-4a5a-ae76-30bf251c7862/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F680e41e6-722a-4a5a-ae76-30bf251c7862%2Fblob)
