### ISSUE TITLE
Multi-Issue Sign Up Modal

### ISSUE THREAD

**Issue by snuka** [ycha28/resume_fixer#99]
The signup page says that the minimum password length is 6 letters but if you insert a 6 letter password, it leads to an error page saying "the password has to be longer than 8 letters"

**Comment by ppzgenome** [comment]
1. We can input <8 letters for password, but there is no alert. Then, if you click sign up, it redirects us to the static log in, which we want to avoid. 

![uploads/f7214ffa-8477-4680-bf57-6b59bd369762/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff7214ffa-8477-4680-bf57-6b59bd369762%2Fblob)
